export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED';

export const NOTIF_PENDING = 'NOTIF_PENDING';
export const NOTIF_ERROR = 'NOTIF_ERROR';
export const NOTIF_SUCCESS = 'NOTIF_SUCCESS';

export const LOCATIONS_PENDING = 'LOCATIONS_PENDING';
export const LOCATIONS_ERROR = 'LOCATIONS_ERROR';
export const LOCATIONS_SUCCESS = 'LOCATIONS_SUCCES';

export const ALERTS_PENDING = 'ALERTS_PENDING';
export const ALERTS_ERROR = 'ALERTS_ERROR';
export const ALERTS_SUCCESS = 'ALERTS_SUCCES';

export const VIDEOS_PENDING = 'VIDEOS_PENDING';
export const VIDEOS_ERROR = 'VIDEOS_ERROR';
export const VIDEOS_SUCCESS = 'VIDEOS_SUCCES';

export const BIV_INFO_PENDING = 'BIV_INFO_PENDING';
export const BIV_INFO_ERROR = 'BIV_INFO_ERROR';
export const BIV_INFO_SUCCESS = 'BIV_INFO_SUCCES';

export const MISSIONS_PENDING = 'MISSIONS_PENDING';
export const MISSIONS_ERROR = 'MISSIONS_ERROR';
export const MISSIONS_SUCCESS = 'MISSIONS_SUCCES';


export const DATA_GRAPHS_PENDING = 'DATA_GRAPHS_PENDING';
export const DATA_GRAPHS_ERROR = 'DATA_GRAPHS_ERROR';
export const DATA_GRAPHS_SUCCESS = 'DATA_GRAPHS_SUCCES';