export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED';

export const WISHES_PENDING = 'WISHES_PENDING';
export const WISHES_ERROR = 'WISHES_ERROR';
export const WISHES_SUCCESS = 'WISHES_SUCCESS';

export const ADD_WISH_PENDING = 'ADD_WISH_PENDING';
export const ADD_WISH_ERROR = 'ADD_WISH_ERROR';
export const ADD_WISH_SUCCESS = 'ADD_WISH_SUCCESS';