# create a docker-compose.yml file
version: "2"
services:
  web:
    build: .
    ports:
      - "2222:4000"
    volumes:
      - ./:/application
      - /application/node_modules
    links:
      - db:db
    environment:
      - DB_HOST=db
      - DB_DATABASE=extension
      - DB_USER=extension_api
      - DB_PASSWORD=extension_api
  db:
    image: mysql:5.6
    volumes:
    # Use this option to persist the MySQL DBs in a shared volume.
    - ./mysqldata:/var/lib/mysql:rw,delegated
    # Use this option to persist the MySQL DBs in a data volume.
    # - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=extension
      - MYSQL_USER=extension_api
      - MYSQL_PASSWORD=extension_api
      - MYSQL_ROOT_PASSWORD=J4m432423ass
    # volumes:
    #   - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: J4m432423ass
    ports:
      - "8080:80"
  
  localtunnel:
    image: efrecon/localtunnel
    links:
      - web
    command:
      --local-host web --port 4000 --subdomain wishlist-backend